### PR TITLE
* meson.build dependencies PIC, seticor lib and dep definitions

### PR DESCRIPTION
**Pull request by radonnachie**
This allows seticore to easily be included as a meson subproject.

### CODE REVIEW

**Comment by radonnachie** [comment]
With these changes I can submodule and compile seticore into BLADE.

**Comment by lacker** [comment]
Cool. Can you just verify that the unit tests run after this change? Run ‘unit_tests.sh’

**Comment by eli-schwartz** [comment]
For fmt, at least, I would actually suggest:
- use `dependency('fmt')`, as many people might already have it installed and can then use the one they already have
- delete the current subproject, and instead use `meson wrap install fmt`, which installs a pure-meson version of fmt from https://wrapdb.mesonbuild.com/ that handles this correctly in one line instead of four. :)

**Comment by radonnachie** [comment]
```
radonn@cosmic-gpu-0:/home/cosmic/dev/blade/subprojects/seticore$ ./unit_tests.sh 
unit testing...
===============================================================================
All tests passed (22 assertions in 6 test cases)

downloading h5 data for regression testing...
```

**Comment by lacker** [comment]
Looks good to me, thanks!

**Comment by lacker** [comment]
I had to revert this change, more or less, in https://github.com/lacker/seticore/commit/829f32cbf0c2159e1bdfc6c746eeaa2a3e41174c - it's breaking meerkat production because the built binary, when copied to a different location during the deployment process, is now failing with

```
error while loading shared libraries: libfmt.so: cannot open shared object file: No such file or directory
```

To double-check you can just ensure the built binary continues to work when copied to a different location. I think this is probably related to the wrap stuff that Eli suggested rather than the library stuff, but it wasn't clear to me how to have one without the other.

**Comment by eli-schwartz** [comment]
CMake is defaulting to build a static fmt, probably. Because BUILD_SHARED_LIBS (global setting) defaults to off.

You can trivially do that with Meson too, simply configure Meson with `-Dfmt:default_library=static`, or more likely (so that you don't have to manually pass arguments to the build), pass `default_options: ['default_library=static']` as a kwarg to the fmt ~~dependency~~ subproject lookup.

Either approach causes the fmt subproject to build its libraries as static archives instead of a DSO -- hence, fmt becomes included in the binary rather than requiring to load some `*.so` file.


(It is still worth using `dependency('fmt')` instead of `subproject('fmt').get_variable('fmt_dep')`, because you can avoid building fmt if you already have one.)

**Comment by lacker** [comment]
I took another look at using this meson wrap but with `default_options: ['default_library=static']` I get the same error. I tried both on the subproject lookup and on the overall project default_options.

**Pull request merged**
